

/**
* -*- C++ -*-
* -------------------------------------------------------------------------------
* - °Ë®q°–®r ®q°–®r					 DataBase_Manager.H,v 1.0 2005/03/25 10:50:54
*  ®u®ê®Ä®Ä®é ®q®q °–®r
* ¶ÚÃÔ¶ÚÃÔÃÔ| ®t------
* -------------------------------------------------------------------------------
*/

#ifndef _DataBase_Manager_H_
#define _DataBase_Manager_H_


#if !defined (BOE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* BOE_LACKS_PRAGMA_ONCE */

#include "config.h"
#include "../serialize/serialize2.h"
#include "db/DbManager.h"
_bt_begin

class DataBase_Pool
{
public:



};


_bt_end

#endif // _DataBase_Manager_H_