

#ifndef _Config_GreenGown_H
#define _Config_GreenGown_H


#include "config.h"

#if !defined (BOE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* BOE_LACKS_PRAGMA_ONCE */

#include "BOE/Logger.H"
#include "../im.h"
#define _greengown_begin
#define _greengown_end
#define _greengown

#ifndef IMLoggerPtr
#define IMLoggerPtr BOE_Log_Impl*
#endif 


_greengown_begin

_greengown_end

#endif // _Config_Networks_H