

/**
* -*- C++ -*-
* -------------------------------------------------------------------------------
* - °Ë®q°–®r ®q°–®r						   config_Memory.H,v 1.0 2006/02/02 14:09
*  ®u®ê®Ä®Ä®é ®q®q °–®r
* ¶ÚÃÔ¶ÚÃÔÃÔ| ®t------
* -------------------------------------------------------------------------------
*/

#ifndef _config_Memory_H_
#define _config_Memory_H_


#include "jomoo/config.h"

#if !defined (JOMOO_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* JOMOO_LACKS_PRAGMA_ONCE */

#include <memory>

#define _jomoo_memory_begin _jomoo_begin
#define _jomoo_memory_end _jomoo_end

#define _jomoo_memory _jomoo
#endif // _config_Memory_H_